# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1d551b280a9b99d3a18c9ea665d242b3aff3a96b75d2ad385471c6cf04da3566e562f2395d93df9fd45e0af3ab59a789c8cf8b8cc4084780e8236f7d9d04e27

test:
  secret_key_base: 6de09141599254362bd18c6cc0ab8c5790b68d4df2019d1accbca973dba8cb207d64eb72d644ab7e4ecc193e5a6dfb91af477b677f9c6cebcec883628d3e97e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
